/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2019-03-27 16:46:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Text_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gbk");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gbk\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery.qrcode.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery.slides.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<Style>\r\n");
      out.write(".index_banner{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tmargin-left:7px;\r\n");
      out.write("\twidth:689px;\r\n");
      out.write("\theight:250px;\r\n");
      out.write("\tbox-shadow:3px 3px 5px #bbb;\r\n");
      out.write("\toverflow:hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search_no{\r\n");
      out.write("\twidth:205px;\r\n");
      out.write("\theight:125px;\r\n");
      out.write("\tline-height:25px;\r\n");
      out.write("\tfont-size:14px;\r\n");
      out.write("\toverflow-y: auto;\r\n");
      out.write("\tborder:1px #dddddd solid;\r\n");
      out.write("\tborder-top:2px #ffce00 solid;\r\n");
      out.write("\tbackground:url(img/bg_text.png);\r\n");
      out.write("\tresize: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</Style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"index_banner\">\r\n");
      out.write("\t<img src=\"5c8f60214ca3f.jpg\" width=\"689\" height=\"225\" alt=\"\">\r\n");
      out.write("\t<img src=\"5c8f6008cf147.jpg\" width=\"689\" height=\"225\" alt=\"\">\r\n");
      out.write("\t<img src=\"/153110011/the_end/yanzhenma_0418/code.php\" width=\"689\" height=\"225\" alt=\"\">\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"qrcodediv\" class=\"login-button\">div内容\r\n");
      out.write("\r\n");
      out.write("<canvas id=\"qrcode\" width=\"256\" height=\"256\"></canvas>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");

String qr = request.getAttribute("qrcode").toString();
System.out.println(qr);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("test\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("打印二维码:<input name=\"b_print\" type=\"button\" class=\"ipt\" onClick=\"printdiv('qrcode');\" value=\" Print \">\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() { \r\n");
      out.write("\t$('.index_banner').slidesjs({\r\n");
      out.write("        width: 680,\r\n");
      out.write("        height: 225,\r\n");
      out.write("        generateNextPrev: true,\r\n");
      out.write("        navigation: true,\r\n");
      out.write("        play: {\r\n");
      out.write("          active: true,\r\n");
      out.write("          auto: true,\r\n");
      out.write("          interval: 6000,\r\n");
      out.write("          swap: true\r\n");
      out.write("        }\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function printdiv(printpage)\r\n");
      out.write("{\r\n");
      out.write("var headstr = \"<html><head><title></title></head><body>\";\r\n");
      out.write("var footstr = \"</body>\";\r\n");
      out.write("var newstr = document.all.item(printpage).innerHTML;\r\n");
      out.write("var oldstr = document.body.innerHTML;\r\n");
      out.write("document.body.innerHTML = headstr+newstr+footstr;\r\n");
      out.write("window.print(); \r\n");
      out.write("document.body.innerHTML = oldstr;\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function utf16to8(str) {  \r\n");
      out.write("    var out, i, len, c;  \r\n");
      out.write("    out = \"\";  \r\n");
      out.write("    len = str.length;  \r\n");
      out.write("    for (i = 0; i < len; i++) {  \r\n");
      out.write("        c = str.charCodeAt(i);  \r\n");
      out.write("        if ((c >= 0x0001) && (c <= 0x007F)) {  \r\n");
      out.write("            out += str.charAt(i);  \r\n");
      out.write("        } else if (c > 0x07FF) {  \r\n");
      out.write("            out += String.fromCharCode(0xE0 | ((c >> 12) & 0x0F));  \r\n");
      out.write("            out += String.fromCharCode(0x80 | ((c >> 6) & 0x3F));  \r\n");
      out.write("            out += String.fromCharCode(0x80 | ((c >> 0) & 0x3F));  \r\n");
      out.write("        } else {  \r\n");
      out.write("            out += String.fromCharCode(0xC0 | ((c >> 6) & 0x1F));  \r\n");
      out.write("            out += String.fromCharCode(0x80 | ((c >> 0) & 0x3F));  \r\n");
      out.write("        }  \r\n");
      out.write("    }  \r\n");
      out.write("    return out;  \r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t$('.login-button').click(function(){\r\n");
      out.write("\t\talert(\"Hello\");\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("jQuery(function(){\r\n");
      out.write("\r\n");
      out.write("\tjQuery('#qrcode').qrcode(utf16to8(");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("));\r\n");
      out.write("\tvar str = '");
      out.print(qr);
      out.write("';\r\n");
      out.write("\tjQuery('#qrcodediv').qrcode(utf16to8(str));\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t//printdiv(\"qrcode\");\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /Text.jsp(138,35) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue("\"&lt要显示的数据对象&gt\"");
      // /Text.jsp(138,35) name = escapeXml type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setEscapeXml(false);
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fescapeXml_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
